<?php
	return array(
		'white'				=>	'01',
		'nude'				=>	'11',
		'beige'				=>	'21',
		'dark beige'		=>	'31',
		'gold'				=>	'02',
		'silver'			=>	'12',
		'copper'			=>	'22',
		'bronze'			=>	'32',
		'blue'				=>	'03',
		'dark blue'			=>	'13',
		'light blue'		=>	'23',
		'l/light blue'		=>	'33',
		'red'				=>	'04',
		'dark red'			=>	'04B',
		'maroon'			=>	'14',
		'pink'				=>	'24',
		'paster pink'		=>	'34',
		'l/light pink'		=>	'44',
		'brown'				=>	'05',
		'dark brown'		=>	'15',
		'light brown'		=>	'25',
		'camel'				=>	'35',
		'dark coffee'		=>	'45',
		'green'				=>	'06',
		'dark green'		=>	'16',
		'light green'		=>	'26',
		'khaki'				=>	'36',
		'yellow'			=>	'07',
		'orange'			=>	'17',
		'light yellow'		=>	'27',
		'dark yellow'		=>	'37',
		'black'				=>	'08',
		'dark grey'			=>	'18',
		'light grey'		=>	'28',
		'l/light grey'		=>	'38',
		'purple'			=>	'09',
		'dark purple'		=>	'19',
		'light purple'		=>	'29',
		'l/light purple'	=>	'39',
		'multi colour'		=>	'00',
		'na'				=>  '00',
		'-'					=>	'00'
	);
?>