<?php
return [
    'fm_hubwire' => [
        'name'          => 'FM Hubwire Sdn Bhd',
        'address'       => [
            'line_1'    => 'Unit 17-7, Level 7, Block C1,',
            'line_2'    => 'Dataran Prima, Jalan PJU 1/41,',
            'line_3'    => '47301 Petaling Jaya, Malaysia',
        ],
        'gst_reg_no'    => '001584476160',
        'tel'           => '',
        'fax'           => '',
        'email'         => '',
        'logo_src'      => 'images/fmhw-logo.png',
    ],
    'hubwire' => [
        'name'          => 'Hubwire Sdn Bhd',
        'address'       => [
            'line_1'    => 'Unit 17-7, Level 7, Block C1,',
            'line_2'    => 'Dataran Prima, Jalan PJU 1/41,',
            'line_3'    => '47301 Petaling Jaya, Malaysia',
        ],
        'gst_reg_no'    => '001817251840',
        'tel'           => '',
        'fax'           => '',
        'email'         => '',
        'logo_src'      => 'images/fmhw-logo.png',
    ],
    'omniscient' => [
        'name'          => 'Omniscient Sdn Bhd',
        'address'       => [
            'line_1'    => 'Lot G341, Ground Floor, New Wing,',
            'line_2'    => '1 utama Shopping Centre,',
            'line_3'    => '1 Lebuh Bandar Utama,',
            'line_4'    => '47800 Petaling Jaya,',
            'line_5'    => 'Selangor, Malaysia.',
        ],
        'gst_reg_no'    => '001875091456',
        'tel'           => '',
        'fax'           => '',
        'email'         => '',
        'logo_src'      => 'images/melissa-logo.png',
    ],
    'citychemo' => [
        'name'          => 'Citychemo Manufacturing Sdn Bhd',
        'address'       => [
            'line_1'    => 'C-6-3A, Capital 3,',
            'line_2'    => '2, Jalan PJU 1A/7A,',
            'line_3'    => 'Oasis Square, Ara Damansara,',
            'line_4'    => '47301 Petaling Jaya,',
            'line_5'    => 'Selangor Darul Ehsan, Malaysia.',
        ],
        'gst_reg_no'    => '000858501120',
        'tel'           => '',
        'fax'           => '',
        'email'         => '',
        'logo_src'      => 'images/badlab-logo.png',
        'logo_src2'     => 'images/gvc-logo.png',
    ],
    'fabspy' => [
        'name'          => 'Fabspy Sdn Bhd',
        'address'       => [
            'line_1'    => 'T008 Level 3, Mid Valley Megamall,',
            'line_2'    => 'Lingkaran Syed Putra, Mid Valley City,',
            'line_3'    => 'Kuala Lumpur, 59200 Malaysia.',
        ],
        'gst_reg_no'    => '002033442816',
        'tel'           => '',
        'fax'           => '',
        'email'         => '',
        'logo_src'      => 'images/fabspy-logo.png',
    ],
    'bata' => [
        'name'          => 'Bata Primavera Sdn Bhd',
        'address'       => [
            'line_1'    => 'B-17, Menara Bata,',
            'line_2'    => 'No. 8 Jalan PJU 8/8A,',
            'line_3'    => 'Damansara Perdana,',
            'line_4'    => '47820 Petaling Jaya,',
            'line_5'    => 'Selangor, Malaysia.',
        ],
        'gst_reg_no'    => '001887125504',
        'tel'           => '',
        'fax'           => '',
        'email'         => '',
        'logo_src'      => 'images/bata-logo.png',
    ],
    'polo_haus' => [
        'name'          => 'BRG Polo Haus Sdn Bhd',
        'address'       => [
            'line_1'    => 'Lot 1897B, Jalan KPB 9,',
            'line_2'    => 'Kawasan Perindustrian Kg. Baru Balakong,',
            'line_3'    => 'Seri Kembangan, 43300,',
            'line_4'    => 'Selangor Darul Ehsan, Malaysia.',
        ],
        'gst_reg_no'    => '001434722304',
        'tel'           => '603-896 44 997',
        'fax'           => '603-896 44 991',
        'email'         => 'os@polohaus.com',
        'logo_src'      => 'images/plh-vg-logo.png',
    ],
];